// AUTO-GENERATED by scripts/gen_data_index.mjs — do not edit.
/* eslint-disable */
import d_g_cash4life from "@/data/draws/cash4life.json";
import d_g_daily_grand from "@/data/draws/daily-grand.json";
import d_g_lottario from "@/data/draws/lottario.json";
import d_g_lotto_6_49 from "@/data/draws/lotto-6-49.json";
import d_g_lotto_max from "@/data/draws/lotto-max.json";
import d_g_mega_millions from "@/data/draws/mega-millions.json";
import d_g_megadice from "@/data/draws/megadice.json";
import d_g_new_york_lotto from "@/data/draws/new-york-lotto.json";
import d_g_ontario_49 from "@/data/draws/ontario-49.json";
import d_g_pick_10 from "@/data/draws/pick-10.json";
import d_g_powerball from "@/data/draws/powerball.json";
import d_g_take_5 from "@/data/draws/take-5.json";
import d_g_western_6_49 from "@/data/draws/western-6-49.json";
import d_g_western_max from "@/data/draws/western-max.json";
import s_g_cash4life from "@/data/stats/cash4life.json";
import s_g_daily_grand from "@/data/stats/daily-grand.json";
import s_g_lottario from "@/data/stats/lottario.json";
import s_g_lotto_6_49 from "@/data/stats/lotto-6-49.json";
import s_g_lotto_max from "@/data/stats/lotto-max.json";
import s_g_mega_millions from "@/data/stats/mega-millions.json";
import s_g_megadice from "@/data/stats/megadice.json";
import s_g_new_york_lotto from "@/data/stats/new-york-lotto.json";
import s_g_ontario_49 from "@/data/stats/ontario-49.json";
import s_g_pick_10 from "@/data/stats/pick-10.json";
import s_g_powerball from "@/data/stats/powerball.json";
import s_g_take_5 from "@/data/stats/take-5.json";
import s_g_western_6_49 from "@/data/stats/western-6-49.json";
import s_g_western_max from "@/data/stats/western-max.json";

export const RAW_DRAWS: Record<string, any> = {
  "cash4life": d_g_cash4life,
  "daily-grand": d_g_daily_grand,
  "lottario": d_g_lottario,
  "lotto-6-49": d_g_lotto_6_49,
  "lotto-max": d_g_lotto_max,
  "mega-millions": d_g_mega_millions,
  "megadice": d_g_megadice,
  "new-york-lotto": d_g_new_york_lotto,
  "ontario-49": d_g_ontario_49,
  "pick-10": d_g_pick_10,
  "powerball": d_g_powerball,
  "take-5": d_g_take_5,
  "western-6-49": d_g_western_6_49,
  "western-max": d_g_western_max,
};

export const RAW_STATS: Record<string, any> = {
  "cash4life": s_g_cash4life,
  "daily-grand": s_g_daily_grand,
  "lottario": s_g_lottario,
  "lotto-6-49": s_g_lotto_6_49,
  "lotto-max": s_g_lotto_max,
  "mega-millions": s_g_mega_millions,
  "megadice": s_g_megadice,
  "new-york-lotto": s_g_new_york_lotto,
  "ontario-49": s_g_ontario_49,
  "pick-10": s_g_pick_10,
  "powerball": s_g_powerball,
  "take-5": s_g_take_5,
  "western-6-49": s_g_western_6_49,
  "western-max": s_g_western_max,
};
