// Auto-generates lib/game-data.ts by scanning data/draws and data/stats.
// Runs before `next build` so adding a game = adding config + data (no imports
// to hand-edit). Emits static JSON imports (required by output:"export").
import { readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const drawsDir = join(root, "data", "draws");
const statsDir = join(root, "data", "stats");

const slugsFrom = (dir) =>
  readdirSync(dir)
    .filter((f) => f.endsWith(".json") && !f.startsWith("_"))
    .map((f) => f.replace(/\.json$/, ""))
    .sort();

const drawSlugs = slugsFrom(drawsDir);
const statSlugs = slugsFrom(statsDir);
const id = (s) => "g_" + s.replace(/[^a-z0-9]/gi, "_");

let out = "// AUTO-GENERATED by scripts/gen_data_index.mjs — do not edit.\n";
out += "/* eslint-disable */\n";
for (const s of drawSlugs) out += `import d_${id(s)} from "@/data/draws/${s}.json";\n`;
for (const s of statSlugs) out += `import s_${id(s)} from "@/data/stats/${s}.json";\n`;
out += "\nexport const RAW_DRAWS: Record<string, any> = {\n";
for (const s of drawSlugs) out += `  ${JSON.stringify(s)}: d_${id(s)},\n`;
out += "};\n\nexport const RAW_STATS: Record<string, any> = {\n";
for (const s of statSlugs) out += `  ${JSON.stringify(s)}: s_${id(s)},\n`;
out += "};\n";

writeFileSync(join(root, "lib", "game-data.ts"), out);
console.log(`gen_data_index: ${drawSlugs.length} draw files, ${statSlugs.length} stat files`);
