-- Lottizen data layer — SQLite (data/lottizen.db) → Supabase Postgres.
--
-- Faithful port of the four production tables. Design choices:
--   * Date/timestamp columns stay `text` (ISO-8601 strings, exactly as SQLite
--     stored them, e.g. '2009-09-25', '2026-07-03T03:49:54+00:00'). The scraper
--     upserts and multi-source verification compare these as strings; keeping
--     text preserves that logic byte-for-byte (the migration brief: "保持幂等
--     upsert 和多源校验逻辑不变"). Do NOT "improve" these to date/timestamptz
--     without re-auditing every comparison in scrape_*.py / calculate_*.py.
--   * SQLite REAL → double precision; INTEGER → integer.
--   * `verified` stays integer (0/1), not boolean — scripts read it as 0/1.
--   * draws keeps the composite PK (game_id, draw_date) — the upsert conflict key.
--
-- Security: RLS is enabled on every table with NO policies, and anon/authenticated
-- are REVOKEd — so the anon/publishable key can read nothing. Only the service
-- role (which bypasses RLS) can read/write. This is the whole point of the move:
-- the data tables are never publicly readable (migration brief step 3).

begin;

-- ---------------------------------------------------------------------------
-- games  (scratch/instant games)
-- ---------------------------------------------------------------------------
create table if not exists public.games (
  game_number     text primary key,
  name            text not null,
  slug            text not null,
  price           double precision not null,
  overall_odds    double precision,
  top_prize_odds  double precision,
  source          text not null,
  scraped_at      text not null
);

-- ---------------------------------------------------------------------------
-- prize_tiers  (scratch prize breakdown, one game → many tiers)
-- ---------------------------------------------------------------------------
create table if not exists public.prize_tiers (
  -- identity starts at 100000, safely above the imported historical ids (max
  -- 4127), so REST-imported rows keep their explicit ids and future auto-inserts
  -- never collide — no post-import setval needed. Scratch tiers are ephemeral
  -- (deleted + re-inserted each refresh), so the id values carry no meaning.
  id           bigint generated by default as identity (start with 100000) primary key,
  game_number  text not null references public.games(game_number) on delete cascade,
  amount       double precision not null,
  label        text not null,
  total        integer not null,
  remaining    integer not null,
  is_top       integer not null default 0,
  scraped_at   text not null
);
create index if not exists idx_tiers_game on public.prize_tiers(game_number);

-- ---------------------------------------------------------------------------
-- draws  (lottery draw history — the big table, ~95k rows, 11 sources)
-- ---------------------------------------------------------------------------
create table if not exists public.draws (
  game_id     text not null,
  draw_date   text not null,            -- 'YYYY-MM-DD'
  numbers     text not null,            -- comma-separated ints, e.g. '5,17,19,25'
  bonus       integer,
  bonus2      integer,
  jackpot     double precision,
  source      text not null,
  verified    integer not null default 0,
  scraped_at  text not null,
  primary key (game_id, draw_date)
);
-- Draw reads in calculate_stats.py filter/sort by game_id then draw_date; the
-- composite PK already covers (game_id, draw_date) prefix lookups.

-- ---------------------------------------------------------------------------
-- game_meta  (next-draw date + jackpot per live game — the "next_draws" data)
-- ---------------------------------------------------------------------------
create table if not exists public.game_meta (
  game_id         text primary key,
  next_draw_date  text,
  next_jackpot    double precision,
  updated_at      text
);

-- ---------------------------------------------------------------------------
-- Lock down: RLS on, no policies, and revoke the PostgREST public roles.
-- service_role bypasses RLS, so scrapers (write) and the build-time prefetch
-- (read) keep full access with the service key; anon/publishable get nothing.
-- ---------------------------------------------------------------------------
alter table public.games       enable row level security;
alter table public.prize_tiers enable row level security;
alter table public.draws       enable row level security;
alter table public.game_meta   enable row level security;

revoke all on public.games,       public.prize_tiers,
              public.draws,       public.game_meta
  from anon, authenticated;

-- service_role has bypassrls but still needs table/sequence GRANTs (bypassrls
-- skips policies, not privilege checks). Tables created via the Management API
-- don't inherit Supabase's default service_role grants, so grant explicitly.
grant select, insert, update, delete
  on public.games, public.prize_tiers, public.draws, public.game_meta
  to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;
