-- ---------------------------------------------------------------------------
-- News items generated by scripts/news_engine.py from the day's data, behind
-- /news. One row per story (event_key): a story that develops (a jackpot run
-- grows, an unclaimed prize's deadline gets closer) is UPDATED in place —
-- same slug, new text, updated_at moves — rather than published again.
--
-- Every figure in headline/dek/body/table was read from the database or an
-- agency's official list by the detector that wrote the row, and passed the
-- engine's number check (each number in the text must match a value the
-- detector registered). `facts` holds the sourced facts shown on the page.
-- ---------------------------------------------------------------------------
create table if not exists public.news_items (
  id            bigint generated always as identity primary key,
  event_key     text not null unique,
  slug          text not null unique,
  kind          text not null,             -- jackpot_run | jackpot_won | rare_draw | scratch_top_gone | scratch_new | scratch_top10_out | scratch_pool | unclaimed_deadline
  category      text not null check (category in ('draw', 'scratch', 'unclaimed')),
  game          text,
  headline      text not null,
  dek           text not null,
  body          jsonb not null,             -- ["paragraph", ...]
  data_table    jsonb,                      -- {"columns": [...], "rows": [[...], ...]} or null
  facts         jsonb not null,             -- [{"label","value","source","url"}]
  data_date     date not null,              -- the data day the latest version describes
  published_at  timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists idx_news_items_published on public.news_items (published_at desc);

alter table public.news_items enable row level security;
revoke all on public.news_items from anon, authenticated;
grant select, insert, update, delete on public.news_items to service_role;
grant usage, select on all sequences in schema public to service_role;

notify pgrst, 'reload schema';
